/**
 * 六壬动态神煞注册表（纯声明式：数据即实现，解释器在 liurenPanel.ts）。
 * 体系定性（docs/10 §〇）：以流年/流月/流日为太极点起大六壬神煞，与八字原局神煞两套独立体系；
 * 大运/流时不起煞。首发（2026-07-31）＝docs/11 全部「高」置信条目 56 条；第十一轮对齐 iOS「六壬」app 后扩至
 * 131 条，2026-08-05 用户全量核验、全部 status:'已验收'（黄金样本＝docs/12 L 系列，test/liuren-l.test.ts）。
 * 将来新增规则先标 '待验收'（面板橙标）、用户核验后再转 '已验收'。
 * 转译纪律：本表数据自 docs/11 起法口诀独立转译；test/liuren-rules.test.ts 期望值自
 * reference/shensha-diaoyan-20260731.json 古籍原文独立转译——两通道靠测试 diff（docs/10 §〇-3）。
 * 标「＝引擎同表」的一律 import 复用，禁止侧车复制（docs/10 §〇-5）。
 */
import { HUAGAI, JIANGXING, JIESHA, LUSHEN, SUI_QIAN, TAOHUA, TIANDE, TIANSHE, WENCHANG, YIMA, YUEDE } from './tables'

export type LiurenFamily = '岁' | '季' | '月' | '旬' | '日干' | '日支'
export type Season = '春' | '夏' | '秋' | '冬'
export type LiurenStatus = '待验收' | '已验收'

export type LiurenQiFa =
  | { kind: 'ring12'; names: readonly string[]; start: 'anchor' | Readonly<Record<string, string>> }
  | { kind: 'offset'; n: number }
  | { kind: 'branchMap'; table: Readonly<Record<string, string | readonly string[]>> }
  | { kind: 'monthSeq'; start: string; dir: 1 | -1 }
  | { kind: 'seasonMap'; table: Readonly<Record<Season, string | readonly string[]>> }
  | { kind: 'stemMap'; table: Readonly<Record<string, string | readonly string[]>> }
  | { kind: 'xunMap'; table: Readonly<Record<string, string>> }
  | { kind: 'xunDun'; gan: string } // 旬遁干：本旬内该干所配之支，位＝干支（如甲辰旬遁庚＝庚戌）
  | { kind: 'builtin'; fn: 'xunKong' | 'xunShou' | 'tianMa' }

export interface LiurenRule {
  id: string
  /** 显示名，自带消歧后缀（同名异煞必须带体系标签，docs/10 §〇-6） */
  name: string
  aliases?: readonly string[]
  system: '六壬'
  family: LiurenFamily
  qifa: LiurenQiFa
  /** 同位合并：指向同族规则（并入该行）或 ring 槽位（保留独立行＋槽位徽标） */
  mergeInto?: { rule: string; ringName?: string }
  status: LiurenStatus
  /** 起法口诀（验证模式推导链文案） */
  koujue: string
  /** 判柱型：位是干支、对流日柱自查（天赦/天转/地转） */
  judge?: '流日柱'
  sourceRef: string
  note?: string
}

/** 三合绝位（劫煞位）：JIESHA（劫煞位→三合三支）反转，不抄第二份 */
const SANHE_JIE: Record<string, string> = {}
for (const [target, sources] of Object.entries(JIESHA)) for (const s of sources) SANHE_JIE[s] = target

export const SANHE_12_NAMES = ['劫煞', '灾煞', '岁煞', '天煞', '月煞', '地煞', '亡神', '将星', '攀鞍', '驿马', '六厄', '华盖'] as const

// —— 多规则共享表（岁/月/日支三级同用，单一出处） ——
/** 六合 */
const LIUHE: Record<string, string> = { 子: '丑', 丑: '子', 寅: '亥', 亥: '寅', 卯: '戌', 戌: '卯', 辰: '酉', 酉: '辰', 巳: '申', 申: '巳', 午: '未', 未: '午' }
/** 刑（子卯互刑、寅巳申/丑戌未三刑环、辰午酉亥自刑） */
const XING: Record<string, string> = { 子: '卯', 丑: '戌', 寅: '巳', 卯: '子', 辰: '辰', 巳: '申', 午: '午', 未: '丑', 申: '寅', 酉: '酉', 戌: '未', 亥: '亥' }
/** 三合其余两支 */
const SANHE_REST: Record<string, readonly string[]> = {
  申: ['子', '辰'], 子: ['申', '辰'], 辰: ['申', '子'],
  寅: ['午', '戌'], 午: ['寅', '戌'], 戌: ['寅', '午'],
  巳: ['酉', '丑'], 酉: ['巳', '丑'], 丑: ['巳', '酉'],
  亥: ['卯', '未'], 卯: ['亥', '未'], 未: ['亥', '卯'],
}
/** 岁德（阳年＝年干自身，阴年＝所合阳干）与岁德合（岁德之合） */
const SUIDE: Record<string, string> = { 甲: '甲', 乙: '庚', 丙: '丙', 丁: '壬', 戊: '戊', 己: '甲', 庚: '庚', 辛: '丙', 壬: '壬', 癸: '戊' }
const SUIDE_HE: Record<string, string> = { 甲: '己', 乙: '乙', 丙: '辛', 丁: '丁', 戊: '癸', 己: '己', 庚: '乙', 辛: '辛', 壬: '丁', 癸: '癸' }

export const LIUREN_RULES: readonly LiurenRule[] = [
  // ── 岁族（8）：以流年支为太岁起 ─────────────────────────────
  {
    id: 'suiQian12',
    name: '岁前十二神',
    system: '六壬',
    family: '岁',
    qifa: { kind: 'ring12', names: SUI_QIAN, start: 'anchor' },
    status: '已验收',
    koujue: '流年支＝太岁顺行：太岁太阳丧门太阴官符死符岁破龙德白虎福德吊客病符',
    sourceRef: 'docs/11:13＋六壬大全卷一（维基文库）',
    note: '已裁决双轨：总览留原局年支版，此为流年支动态版；names＝引擎 SUI_QIAN 同表 import 复用',
  },
  {
    id: 'sanhe12',
    name: '三合十二煞',
    system: '六壬',
    family: '岁',
    qifa: { kind: 'ring12', names: SANHE_12_NAMES, start: SANHE_JIE },
    status: '已验收',
    koujue: '自流年三合绝位起劫煞顺行：劫煞灾煞岁煞天煞月煞地煞亡神将星攀鞍驿马六厄华盖',
    sourceRef: 'docs/11:14＋六壬大全卷一（维基文库）',
    note: '紫微系「将前十二神」为同物异名（五位名不同），按六壬大全口径（docs/10 §〇-4）；起点＝JIESHA 反转（三合绝位），不抄第二份',
  },
  {
    id: 'daHao',
    name: '大耗',
    system: '六壬',
    family: '岁',
    qifa: { kind: 'offset', n: 6 },
    mergeInto: { rule: 'suiQian12', ringName: '岁破' },
    status: '已验收',
    koujue: '岁冲（太岁对冲支，与岁破同位）',
    sourceRef: 'docs/11:15＋六壬大全卷一（维基文库）',
  },
  {
    id: 'xiaoHao',
    name: '小耗',
    system: '六壬',
    family: '岁',
    qifa: { kind: 'offset', n: 5 },
    mergeInto: { rule: 'suiQian12', ringName: '死符' },
    status: '已验收',
    koujue: '岁前五辰（与死符同位）',
    sourceRef: 'docs/11:16＋六壬大全卷一（维基文库）',
  },
  {
    id: 'huangFan',
    name: '黄幡',
    system: '六壬',
    family: '岁',
    qifa: { kind: 'branchMap', table: HUAGAI },
    status: '已验收',
    koujue: '流年三合墓辰',
    sourceRef: 'docs/11:17＋六壬大全卷一（维基文库）',
    note: '＝引擎华盖同表（三合墓库）import 复用',
  },
  {
    id: 'baoWei',
    name: '豹尾',
    system: '六壬',
    family: '岁',
    qifa: {
      kind: 'branchMap',
      table: { 子: '戌', 丑: '未', 寅: '辰', 卯: '丑', 辰: '戌', 巳: '未', 午: '辰', 未: '丑', 申: '戌', 酉: '未', 戌: '辰', 亥: '丑' },
    },
    status: '已验收',
    koujue: '黄幡对冲',
    sourceRef: 'docs/11:18＋六壬大全卷一（维基文库）',
    note: '独立转录表，禁止由 HUAGAI 推导——「豹尾＝黄幡冲」派生关系交给不变量测试交叉校验',
  },
  {
    id: 'bingFu',
    name: '病符',
    system: '六壬',
    family: '岁',
    qifa: { kind: 'offset', n: -1 },
    mergeInto: { rule: 'suiQian12', ringName: '病符' },
    status: '已验收',
    koujue: '岁后一辰（旧太岁，与岁前十二神第12位病符同位）',
    sourceRef: 'docs/11:19＋六壬大全卷一（维基文库）',
  },
  {
    id: 'suiHu',
    name: '岁虎',
    aliases: ['白虎(岁)'],
    system: '六壬',
    family: '岁',
    qifa: { kind: 'offset', n: -4 },
    mergeInto: { rule: 'suiQian12', ringName: '白虎' },
    status: '已验收',
    koujue: '岁后四辰（与岁前十二神第9位白虎同位）',
    sourceRef: 'docs/11:20＋六壬大全卷一（维基文库）',
  },
  // ── 季族（12）：按流月支所属季起 ────────────────────────────
  {
    id: 'tianMu',
    name: '天目',
    system: '六壬',
    family: '季',
    qifa: { kind: 'seasonMap', table: { 春: '辰', 夏: '未', 秋: '戌', 冬: '丑' } },
    status: '已验收',
    koujue: '春辰夏未秋戌冬丑',
    sourceRef: 'docs/11:31＋六壬大全卷一（维基文库）',
    note: '六壬大全另有同位「月符」',
  },
  {
    id: 'tianEr',
    name: '天耳',
    system: '六壬',
    family: '季',
    qifa: { kind: 'seasonMap', table: { 春: '戌', 夏: '丑', 秋: '辰', 冬: '未' } },
    status: '已验收',
    koujue: '天目对冲：春戌夏丑秋辰冬未',
    sourceRef: 'docs/11:32＋六壬大全卷一（维基文库）',
  },
  {
    id: 'tianXiJi',
    name: '天喜',
    aliases: ['天喜(季)'],
    system: '六壬',
    family: '季',
    qifa: { kind: 'seasonMap', table: { 春: '戌', 夏: '丑', 秋: '辰', 冬: '未' } },
    mergeInto: { rule: 'tianEr' },
    status: '已验收',
    koujue: '春戌夏丑秋辰冬未（与天耳同位）',
    sourceRef: 'docs/11:33＋六壬大全卷一（维基文库）',
    note: '与八字年支版天喜同名异煞，须标体系',
  },
  {
    id: 'xiShen',
    name: '戏神',
    system: '六壬',
    family: '季',
    qifa: { kind: 'seasonMap', table: { 春: '巳', 夏: '子', 秋: '酉', 冬: '辰' } },
    status: '已验收', // 2026-08-05 用户裁决保持三家一致表；app「戏神」行的值另由 youShenDq 承接
    koujue: '春巳夏子秋酉冬辰',
    sourceRef: 'docs/11:34＋六壬大全卷一（维基文库）',
  },
  {
    id: 'siFeiZhi',
    name: '四废',
    aliases: ['四废(支版)'],
    system: '六壬',
    family: '季',
    qifa: { kind: 'seasonMap', table: { 春: '酉', 夏: '子', 秋: '卯', 冬: '午' } },
    status: '已验收',
    koujue: '春酉夏子秋卯冬午',
    sourceRef: 'docs/11:35＋六壬大全卷一（维基文库）',
    note: '与八字正四废日（干支版，引擎已有）同名异煞，须标体系',
  },
  {
    id: 'jiGu',
    name: '孤辰',
    aliases: ['孤辰(季)'],
    system: '六壬',
    family: '季',
    qifa: { kind: 'seasonMap', table: { 春: '巳', 夏: '申', 秋: '亥', 冬: '寅' } },
    status: '已验收',
    koujue: '春巳夏申秋亥冬寅',
    sourceRef: 'docs/11:36＋六壬大全卷一（维基文库）',
    note: '与八字年支版孤辰同名异煞，须标体系',
  },
  {
    id: 'jiGua',
    name: '寡宿',
    aliases: ['寡宿(季)'],
    system: '六壬',
    family: '季',
    qifa: { kind: 'seasonMap', table: { 春: '丑', 夏: '辰', 秋: '未', 冬: '戌' } },
    status: '已验收',
    koujue: '春丑夏辰秋未冬戌',
    sourceRef: 'docs/11:36＋六壬大全卷一（维基文库）',
    note: '与八字年支版寡宿同名异煞，须标体系',
  },
  {
    id: 'heSan',
    name: '喝散',
    system: '六壬',
    family: '季',
    qifa: { kind: 'seasonMap', table: { 春: '巳', 夏: '申', 秋: '亥', 冬: '寅' } },
    mergeInto: { rule: 'jiGu' },
    status: '已验收',
    koujue: '春巳夏申秋亥冬寅（与季孤辰同位）',
    sourceRef: 'docs/11:37＋六壬大全卷一（维基文库）',
  },
  {
    id: 'sangChe',
    name: '丧车煞',
    aliases: ['丧车(季)'],
    system: '六壬',
    family: '季',
    qifa: { kind: 'seasonMap', table: { 春: '酉', 夏: '子', 秋: '卯', 冬: '午' } },
    mergeInto: { rule: 'siFeiZhi' },
    status: '已验收',
    koujue: '春酉夏子秋卯冬午（与四废同位）',
    sourceRef: 'docs/11:38＋六壬大全卷一（维基文库）',
  },
  {
    id: 'guanShen',
    name: '关神',
    system: '六壬',
    family: '季',
    qifa: { kind: 'seasonMap', table: { 春: '丑', 夏: '辰', 秋: '未', 冬: '戌' } },
    mergeInto: { rule: 'jiGua' },
    status: '已验收',
    koujue: '春丑夏辰秋未冬戌（与季寡宿同位）',
    sourceRef: 'docs/11:39＋六壬大全卷一（维基文库）',
  },
  {
    id: 'tianZhuan',
    name: '天转',
    system: '六壬',
    family: '季',
    qifa: { kind: 'seasonMap', table: { 春: '乙卯', 夏: '丙午', 秋: '辛酉', 冬: '壬子' } },
    status: '已验收',
    koujue: '春乙卯夏丙午秋辛酉冬壬子（季锚→判流日柱干支）',
    judge: '流日柱',
    sourceRef: 'docs/11:40＋六壬大全卷一（维基文库）',
  },
  {
    id: 'diZhuan',
    name: '地转',
    system: '六壬',
    family: '季',
    qifa: { kind: 'seasonMap', table: { 春: '辛卯', 夏: '戊午', 秋: '癸酉', 冬: '丙子' } },
    status: '已验收',
    koujue: '春辛卯夏戊午秋癸酉冬丙子（季锚→判流日柱干支）',
    judge: '流日柱',
    sourceRef: 'docs/11:40＋六壬大全卷一（维基文库）',
  },
  {
    id: 'youShen',
    name: '游神',
    system: '六壬',
    family: '季',
    qifa: { kind: 'seasonMap', table: { 春: '丑', 夏: '子', 秋: '亥', 冬: '戌' } },
    status: '已验收',
    koujue: '春丑夏子秋亥冬戌',
    sourceRef: 'docs/11:41（春丑夏子确定，秋冬两说）＋简书南离生「秋亥冬戌」；docs/12 L2/L7 双锚定案（夏＝子、冬＝戌）',
    note: '原「秋冬两说」由 app 冬月截图裁定：大全说秋戌冬亥被否，取简书说',
  },
  {
    id: 'youShenDq',
    name: '游神·大全本',
    system: '六壬',
    family: '季',
    qifa: { kind: 'seasonMap', table: { 春: '丑', 夏: '子', 秋: '戌', 冬: '亥' } },
    status: '已验收',
    koujue: '春丑夏子秋戌冬亥',
    sourceRef: '六壬大全卷一起例「逰神春丑夏子秋戌冬亥，主行人至」；docs/12 L2/L7（app 于「戏神」行显示此值：夏＝子、冬＝亥）',
    note: '与《六壬指南》系游神（春丑夏子秋亥冬戌）秋冬两位互换；app 把本表挂在「戏神」名下，真戏神三家一致作春巳夏子秋酉冬辰（见 docs/12 附五）',
  },
  {
    id: 'zhuanSha',
    name: '转煞',
    system: '六壬',
    family: '季',
    qifa: { kind: 'seasonMap', table: { 春: '卯', 夏: '午', 秋: '酉', 冬: '子' } },
    status: '已验收',
    koujue: '四季之旺神（四仲）：春卯夏午秋酉冬子',
    sourceRef: 'app 释义「四季之旺神，物极则反」＋四季旺位自明；docs/12 L2/L7 双锚（夏＝午、冬＝子）',
    note: '原列「查不清不做」，由 app 冬月截图补第二锚后起法自明（四季旺位即四仲），故转入',
  },
  // ── 月族（18）：以流月支（月建）起 ──────────────────────────
  {
    id: 'yueDeLr',
    name: '月德(支系)',
    system: '六壬',
    family: '月',
    qifa: {
      kind: 'branchMap',
      table: { 寅: '巳', 卯: '寅', 辰: '亥', 巳: '申', 午: '巳', 未: '寅', 申: '亥', 酉: '申', 戌: '巳', 亥: '寅', 子: '亥', 丑: '申' },
    },
    status: '已验收',
    koujue: '巳寅亥申三轮（正月巳）',
    sourceRef: 'docs/11:48＋六壬大全卷一（维基文库）',
    note: '与八字月德贵人（查天干）及六壬app干系月德（yueDeGan）均同名异煞，须标注；app 未显示此条，用户裁决保留',
  },
  {
    id: 'shengQi',
    name: '生气',
    system: '六壬',
    family: '月',
    qifa: { kind: 'monthSeq', start: '子', dir: 1 },
    status: '已验收',
    koujue: '正月起子顺行',
    sourceRef: 'docs/11:49＋六壬大全卷一（维基文库）',
  },
  {
    id: 'siQi',
    name: '死气',
    system: '六壬',
    family: '月',
    qifa: { kind: 'monthSeq', start: '午', dir: 1 },
    status: '已验收',
    koujue: '正月起午顺行（生气冲）',
    sourceRef: 'docs/11:50＋六壬大全卷一（维基文库）',
  },
  {
    id: 'tianZhao',
    name: '天诏',
    system: '六壬',
    family: '月',
    qifa: { kind: 'monthSeq', start: '亥', dir: 1 },
    status: '已验收',
    koujue: '正月起亥顺行',
    sourceRef: 'docs/11:51＋六壬大全卷一（维基文库）',
  },
  {
    id: 'muMen',
    name: '墓门',
    system: '六壬',
    family: '月',
    qifa: {
      kind: 'branchMap',
      table: { 寅: '亥', 卯: '申', 辰: '巳', 巳: '寅', 午: '亥', 未: '申', 申: '巳', 酉: '寅', 戌: '亥', 亥: '申', 子: '巳', 丑: '寅' },
    },
    status: '已验收',
    koujue: '亥申巳寅逆行四孟三轮（正月亥）',
    sourceRef: 'docs/11:52＋六壬大全卷一（维基文库）',
  },
  {
    id: 'chengShen',
    name: '成神',
    system: '六壬',
    family: '月',
    qifa: {
      kind: 'branchMap',
      table: { 寅: '巳', 卯: '申', 辰: '亥', 巳: '寅', 午: '巳', 未: '申', 申: '亥', 酉: '寅', 戌: '巳', 亥: '申', 子: '亥', 丑: '寅' },
    },
    status: '已验收',
    koujue: '巳申亥寅顺行四孟三轮（正月巳）',
    sourceRef: 'docs/11:53＋六壬大全卷一（维基文库）',
  },
  {
    id: 'shengXin',
    name: '圣心',
    system: '六壬',
    family: '月',
    qifa: {
      kind: 'branchMap',
      table: { 寅: '亥', 卯: '巳', 辰: '子', 巳: '午', 午: '丑', 未: '未', 申: '寅', 酉: '申', 戌: '卯', 亥: '酉', 子: '辰', 丑: '戌' },
    },
    status: '已验收',
    koujue: '单月起亥、双月起巳各顺行（正亥二巳三子四午五丑六未…）',
    sourceRef: 'docs/11:54＋六壬大全卷一（维基文库）',
  },
  {
    id: 'tianMaYue',
    name: '天马',
    aliases: ['天马(流月)'],
    system: '六壬',
    family: '月',
    qifa: { kind: 'builtin', fn: 'tianMa' },
    status: '已验收',
    koujue: '午顺六阳：正午二申三戌四子五寅六辰',
    sourceRef: 'docs/11:55＋六壬大全卷一（维基文库）',
    note: '＝引擎 tianMa 函数复用，传流月支即动态版；原局月支版留不留待用户裁决',
  },
  {
    id: 'tianWu',
    name: '天巫',
    system: '六壬',
    family: '月',
    qifa: { kind: 'monthSeq', start: '辰', dir: 1 },
    status: '已验收',
    koujue: '正月起辰顺行',
    sourceRef: 'docs/11:56＋六壬大全卷一（维基文库）',
    note: '主婚姻',
  },
  {
    id: 'huangShu',
    name: '皇书',
    system: '六壬',
    family: '季',
    qifa: { kind: 'seasonMap', table: { 春: '寅', 夏: '巳', 秋: '申', 冬: '亥' } },
    status: '已验收',
    koujue: '春寅夏巳秋申冬亥',
    sourceRef: 'docs/11:57＋六壬大全卷一（维基文库）',
    note: '实为季起，习惯归月系',
  },
  {
    id: 'tianSheDyn',
    name: '天赦',
    aliases: ['天赦(判流日)'],
    system: '六壬',
    family: '季',
    qifa: { kind: 'branchMap', table: TIANSHE },
    status: '已验收',
    koujue: '春戊寅夏甲午秋戊申冬甲子（以月建定季、判流日柱干支）',
    judge: '流日柱',
    sourceRef: 'docs/11:58＋六壬大全卷一（维基文库）',
    note: '与八字天赦同表（TIANSHE import 复用），动态版判流日柱',
  },
  {
    id: 'xueZhi',
    name: '血支',
    aliases: ['血支(月系)'],
    system: '六壬',
    family: '月',
    qifa: { kind: 'monthSeq', start: '丑', dir: 1 },
    status: '已验收',
    koujue: '正月起丑顺行',
    sourceRef: 'docs/11:59＋六壬大全卷一（维基文库）',
    note: '与八字血刃（月支系）配对关系待用户说明',
  },
  {
    id: 'xueJi',
    name: '血忌',
    system: '六壬',
    family: '月',
    qifa: {
      kind: 'branchMap',
      table: { 寅: '丑', 卯: '未', 辰: '寅', 巳: '申', 午: '卯', 未: '酉', 申: '辰', 酉: '戌', 戌: '巳', 亥: '亥', 子: '午', 丑: '子' },
    },
    status: '已验收',
    koujue: '阳月丑起、阴月未起各顺行：正丑二未三寅四申五卯六酉七辰八戌九巳十亥冬午腊子',
    sourceRef: 'docs/11:60＋六壬大全卷一（维基文库）',
    note: '兼择日凶神',
  },
  {
    id: 'yueYan',
    name: '月厌',
    system: '六壬',
    family: '月',
    qifa: { kind: 'monthSeq', start: '戌', dir: -1 },
    status: '已验收',
    koujue: '正月起戌逆行',
    sourceRef: 'docs/11:61＋六壬大全卷一（维基文库）',
    note: '兼择日凶神',
  },
  {
    id: 'wangWang',
    name: '往亡',
    system: '六壬',
    family: '月',
    qifa: {
      kind: 'branchMap',
      table: { 寅: '寅', 卯: '巳', 辰: '申', 巳: '亥', 午: '卯', 未: '午', 申: '酉', 酉: '子', 戌: '辰', 亥: '未', 子: '戌', 丑: '丑' },
    },
    status: '已验收',
    koujue: '正寅二巳三申四亥五卯六午七酉八子九辰十未冬戌腊丑',
    sourceRef: 'docs/11:62＋六壬大全卷一（维基文库）',
    note: '兼择日凶神',
  },
  {
    id: 'yuePo',
    name: '月破',
    system: '六壬',
    family: '月',
    qifa: { kind: 'offset', n: 6 },
    status: '已验收',
    koujue: '月建对冲',
    sourceRef: 'docs/11:63＋六壬大全卷一（维基文库）',
    note: '兼择日凶神',
  },
  {
    id: 'sanQiu',
    name: '三丘',
    system: '六壬',
    family: '季',
    qifa: { kind: 'seasonMap', table: { 春: '辰', 夏: '未', 秋: '戌', 冬: '丑' } },
    mergeInto: { rule: 'tianMu' },
    status: '已验收',
    koujue: '四季长生之墓：春木长生亥（水）→水墓辰；夏火长生寅（木）→木墓未；秋金长生巳（火）→火墓戌；冬水长生申（金）→金墓丑（与天目同位）',
    sourceRef: '六壬大全卷一逐月神煞＋六壬指南卷四＋伊凡子（三家一致）；docs/11:64',
    note: '2026-08-02 用户亲授起法定案（原话：三丘就是四季长生的墓地——寅卯辰月是木、木长生在亥、水之墓是辰），app 夏＝未与冬＝丑两锚均吻合；先前所查三个文献口径全部作废',
  },
  {
    id: 'wuMu',
    name: '五墓',
    system: '六壬',
    family: '季',
    qifa: { kind: 'seasonMap', table: { 春: '未', 夏: '戌', 秋: '丑', 冬: '辰' } },
    status: '已验收',
    koujue: '四季五行之墓库：春（木）未、夏（火）戌、秋（金）丑、冬（水）辰＝三丘顺行三位',
    sourceRef: 'docs/11:64＋六壬大全卷一（维基文库）',
    note: '独立转录表，禁止由三丘表推导——对冲关系交给不变量测试交叉校验',
  },
  // ── 旬族（4）：随流日之旬起（docs/10 §〇-7 裁决②）───────────
  {
    id: 'xunKongDyn',
    name: '旬空',
    system: '六壬',
    family: '旬',
    qifa: { kind: 'builtin', fn: 'xunKong' },
    status: '已验收',
    koujue: '六甲旬空两支',
    sourceRef: 'docs/11:76＋六壬大全卷一（维基文库）',
    note: '＝引擎 xunKong 函数复用，对流日柱起',
  },
  {
    id: 'xunYi',
    name: '六仪',
    aliases: ['旬仪', '仪神'],
    system: '六壬',
    family: '旬',
    qifa: { kind: 'builtin', fn: 'xunShou' },
    status: '已验收',
    koujue: '旬首之支（甲子旬在子、甲戌旬在戌…）',
    sourceRef: 'docs/11:77＋六壬大全卷一（维基文库）',
    note: '＝引擎 xunShou 函数复用',
  },
  {
    id: 'xunQi',
    name: '旬奇',
    system: '六壬',
    family: '旬',
    qifa: { kind: 'xunMap', table: { 子: '丑', 戌: '丑', 申: '子', 午: '子', 辰: '亥', 寅: '亥' } },
    status: '已验收',
    koujue: '甲子甲戌旬丑、甲申甲午旬子、甲辰甲寅旬亥',
    sourceRef: 'docs/11:78＋六壬大全卷一（维基文库）',
  },
  {
    id: 'jieLu',
    name: '截路空亡',
    system: '六壬',
    family: '旬',
    qifa: {
      kind: 'stemMap',
      table: {
        甲: ['申', '酉'],
        乙: ['午', '未'],
        丙: ['辰', '巳'],
        丁: ['寅', '卯'],
        戊: ['戌', '亥'],
        己: ['申', '酉'],
        庚: ['午', '未'],
        辛: ['辰', '巳'],
        壬: ['寅', '卯'],
        癸: ['戌', '亥'],
      },
    },
    status: '已验收',
    koujue: '甲己日申酉、乙庚午未、丙辛辰巳、丁壬寅卯、戊癸戌亥——以流日干起、查时支段',
    sourceRef: 'docs/11:79＋六壬大全卷一（维基文库）',
    note: '戊癸一说子丑，取主口径戌亥；实为日干起查时支，归旬族按用户分法',
  },
  // ── 日干族（7）：以流日干起 ────────────────────────────────
  {
    id: 'riLu',
    name: '日禄',
    system: '六壬',
    family: '日干',
    qifa: { kind: 'stemMap', table: LUSHEN },
    status: '已验收',
    koujue: '十干禄：甲寅乙卯丙戊巳丁己午庚申辛酉壬亥癸子',
    sourceRef: 'docs/11:88＋六壬大全卷一（维基文库）',
    note: '＝引擎禄神同表（LUSHEN import 复用）',
  },
  {
    id: 'riDeLr',
    name: '日德',
    aliases: ['日德(六壬)'],
    system: '六壬',
    family: '日干',
    qifa: {
      kind: 'stemMap',
      table: { 甲: '寅', 乙: '申', 丙: '巳', 丁: '亥', 戊: '巳', 己: '寅', 庚: '申', 辛: '巳', 壬: '亥', 癸: '巳' },
    },
    status: '已验收',
    koujue: '甲己寅、乙庚申、丙辛巳、丁壬亥、戊癸巳',
    sourceRef: 'docs/11:89＋六壬大全卷一（维基文库）',
    note: '与八字日德（五日柱）同名异煞，须标体系',
  },
  {
    id: 'yangRenLr',
    name: '羊刃',
    aliases: ['羊刃(六壬)'],
    system: '六壬',
    family: '日干',
    qifa: {
      kind: 'stemMap',
      table: { 甲: '卯', 乙: '辰', 丙: '午', 丁: '未', 戊: '午', 己: '未', 庚: '酉', 辛: '戌', 壬: '子', 癸: '丑' },
    },
    status: '已验收',
    koujue: '禄前一位：甲卯乙辰丙戊午丁己未庚酉辛戌壬子癸丑',
    sourceRef: 'docs/11:90＋六壬大全卷一（维基文库）',
    note: '阴干与子平羊刃不同表，必须标体系；独立转录，禁止由 LUSHEN+1 推导——「禄前一位」关系交给不变量测试',
  },
  {
    id: 'wenChangLr',
    name: '文昌',
    system: '六壬',
    family: '日干',
    qifa: { kind: 'stemMap', table: WENCHANG },
    status: '已验收',
    koujue: '甲巳乙午丙戊申丁己酉庚亥辛子壬寅癸卯',
    sourceRef: 'docs/11:91＋六壬大全卷一（维基文库）',
    note: '与原局文昌同表（WENCHANG import 复用），同名同表不加消歧后缀；六壬另有「文星」不同表（甲乙亥…，中置信单源）不在首发、待用户裁决——2026-07-31 双通道 diff 仲裁记录',
  },
  {
    id: 'fuXingLr',
    name: '福星',
    aliases: ['福星(六壬)'],
    system: '六壬',
    family: '日干',
    qifa: {
      kind: 'stemMap',
      table: { 甲: '子', 乙: '丑', 丙: '子', 丁: '子', 戊: '未', 己: '未', 庚: '丑', 辛: '丑', 壬: '巳', 癸: '巳' },
    },
    status: '已验收',
    koujue: '甲丙丁日子、乙庚辛日丑、戊己日未、壬癸日巳',
    sourceRef: 'docs/11:92＋六壬大全卷一（维基文库）',
    note: '与八字福星贵人不同表，须标体系',
  },
  {
    id: 'zhiFu',
    name: '直符',
    aliases: ['飞符'],
    system: '六壬',
    family: '日干',
    qifa: {
      kind: 'stemMap',
      table: { 甲: '巳', 乙: '辰', 丙: '卯', 丁: '寅', 戊: '丑', 己: '午', 庚: '未', 辛: '申', 壬: '酉', 癸: '戌' },
    },
    status: '已验收',
    koujue: '甲巳乙辰丙卯丁寅戊丑己午庚未辛申壬酉癸戌',
    sourceRef: 'docs/11:93＋六壬大全卷一（维基文库）',
  },
  {
    id: 'ganYi',
    name: '干仪',
    aliases: ['日仪'],
    system: '六壬',
    family: '日干',
    qifa: {
      kind: 'stemMap',
      table: { 甲: '午', 乙: '巳', 丙: '辰', 丁: '卯', 戊: '寅', 己: '丑', 庚: '未', 辛: '申', 壬: '酉', 癸: '戌' },
    },
    status: '已验收',
    koujue: '甲午起逆（甲午乙巳丙辰丁卯戊寅己丑）、庚未起顺（庚未辛申壬酉癸戌）',
    sourceRef: 'docs/11:94＋六壬大全卷一（维基文库）',
  },
  // ── 日支族（7）：以流日支起 ────────────────────────────────
  {
    id: 'zhiMa',
    name: '日马',
    aliases: ['支马'],
    system: '六壬',
    family: '日支',
    qifa: { kind: 'branchMap', table: YIMA },
    status: '已验收',
    koujue: '日支三合首之冲（申子辰在寅…）',
    sourceRef: 'docs/11:105＋六壬大全卷一（维基文库）',
    note: '＝引擎驿马同表（YIMA import 复用）',
  },
  {
    id: 'zhiXing',
    name: '三刑',
    aliases: ['支刑'],
    system: '六壬',
    family: '日支',
    qifa: { kind: 'branchMap', table: XING },
    status: '已验收',
    koujue: '全表：子卯互刑、寅巳申/丑戌未朋刑、辰午酉亥自刑',
    sourceRef: 'docs/11:106＋六壬大全卷一（维基文库）',
  },
  {
    id: 'zhiChong',
    name: '六冲',
    aliases: ['支冲'],
    system: '六壬',
    family: '日支',
    qifa: { kind: 'offset', n: 6 },
    status: '已验收',
    koujue: '六冲对宫',
    sourceRef: 'docs/11:107＋六壬大全卷一（维基文库）',
    note: '2026-08-02 定名六冲（app 口径），「日破」悬案关闭',
  },
  {
    id: 'zhiPo',
    name: '六破',
    aliases: ['支破'],
    system: '六壬',
    family: '日支',
    qifa: {
      kind: 'branchMap',
      table: { 子: '酉', 丑: '辰', 寅: '亥', 卯: '午', 辰: '丑', 巳: '申', 午: '卯', 未: '戌', 申: '巳', 酉: '子', 戌: '未', 亥: '寅' },
    },
    status: '已验收',
    koujue: '六破：子酉丑辰寅亥卯午巳申未戌',
    sourceRef: 'docs/11:108＋六壬大全卷一（维基文库）',
    note: '2026-08-02 定名六破（app 口径），「日破」悬案关闭',
  },
  {
    id: 'zhiHai',
    name: '六害',
    aliases: ['支害'],
    system: '六壬',
    family: '日支',
    qifa: {
      kind: 'branchMap',
      table: { 子: '未', 丑: '午', 寅: '巳', 卯: '辰', 辰: '卯', 巳: '寅', 午: '丑', 未: '子', 申: '亥', 酉: '戌', 戌: '酉', 亥: '申' },
    },
    status: '已验收',
    koujue: '六害：子未丑午寅巳卯辰申亥酉戌',
    sourceRef: 'docs/11:109＋六壬大全卷一（维基文库）',
  },
  {
    id: 'poSui',
    name: '破碎',
    aliases: ['破碎煞'],
    system: '六壬',
    family: '日支',
    qifa: {
      kind: 'branchMap',
      table: { 子: '巳', 丑: '丑', 寅: '酉', 卯: '巳', 辰: '丑', 巳: '酉', 午: '巳', 未: '丑', 申: '酉', 酉: '巳', 戌: '丑', 亥: '酉' },
    },
    status: '已验收',
    koujue: '四仲见巳、四孟见酉、四季见丑',
    sourceRef: 'docs/11:110＋六壬大全卷一（维基文库）',
    note: '与八字破碎（暗金的杀）同表（引擎尚无该常量，此处即数据源）',
  },
  {
    id: 'zhiYi',
    name: '支仪',
    system: '六壬',
    family: '日支',
    qifa: {
      kind: 'branchMap',
      table: { 子: '午', 丑: '巳', 寅: '辰', 卯: '卯', 辰: '寅', 巳: '丑', 午: '未', 未: '申', 申: '酉', 酉: '戌', 戌: '亥', 亥: '子' },
    },
    status: '已验收',
    koujue: '子日午起逆（子午丑巳寅辰卯卯辰寅巳丑）、午日未起顺（午未未申申酉酉戌戌亥亥子）',
    sourceRef: 'docs/11:111＋六壬大全卷一（维基文库）',
  },
  // ══ 2026-08-02 第二批（L 系列样本对齐，docs/12）：公式已知组 25 条 ══
  // ── 岁族新增（6） ──
  {
    id: 'suiDe',
    name: '岁德',
    system: '六壬',
    family: '岁',
    qifa: { kind: 'stemMap', table: SUIDE },
    status: '已验收',
    koujue: '阳年＝年干自身，阴年＝所合阳干（丙午年＝丙）',
    sourceRef: 'docs/12 L1（六壬app 校验丙午＝丙）＋协纪辨方书义例',
  },
  {
    id: 'suiDeHe',
    name: '岁德合',
    system: '六壬',
    family: '岁',
    qifa: { kind: 'stemMap', table: SUIDE_HE },
    status: '已验收',
    koujue: '岁德所合之干（丙午年＝辛）',
    sourceRef: 'docs/12 L1（校验丙午＝辛）＋协纪辨方书义例',
  },
  {
    id: 'suiHe',
    name: '岁合',
    system: '六壬',
    family: '岁',
    qifa: { kind: 'branchMap', table: LIUHE },
    status: '已验收',
    koujue: '太岁六合之支（午年＝未）',
    sourceRef: 'docs/12 L1（校验午＝未）',
  },
  {
    id: 'suiXing',
    name: '岁刑',
    system: '六壬',
    family: '岁',
    qifa: { kind: 'branchMap', table: XING },
    status: '已验收',
    koujue: '太岁之刑（午年自刑在午）',
    sourceRef: 'docs/12 L1（校验午＝午）',
  },
  {
    id: 'suiMu',
    name: '岁墓',
    system: '六壬',
    family: '岁',
    qifa: { kind: 'offset', n: -5 },
    status: '已验收',
    koujue: '岁后五位（午年＝丑）',
    sourceRef: 'docs/11:21（六壬大全）＋docs/12 L1（校验午＝丑）——原中置信单源，app 佐证转实',
  },
  {
    id: 'daJiangJun',
    name: '将军',
    aliases: ['大将军'],
    system: '六壬',
    family: '岁',
    qifa: {
      kind: 'branchMap',
      table: { 亥: '酉', 子: '酉', 丑: '酉', 寅: '子', 卯: '子', 辰: '子', 巳: '卯', 午: '卯', 未: '卯', 申: '午', 酉: '午', 戌: '午' },
    },
    status: '已验收',
    koujue: '方合年顺仲：亥子丑年酉、寅卯辰年子、巳午未年卯、申酉戌年午',
    sourceRef: 'docs/11:22（单源）＋docs/12 L1（校验午＝卯）——app 佐证转实',
  },
  // ── 月族新增（7） ──
  {
    id: 'tianDeYue',
    name: '天德',
    system: '六壬',
    family: '月',
    qifa: { kind: 'branchMap', table: TIANDE },
    status: '已验收',
    koujue: '正丁二申三壬四辛五亥六甲七癸八寅九丙十乙冬巳腊庚（四维月用支）',
    sourceRef: 'docs/12 L3（校验未＝甲）＋引擎 TIANDE 同表 import 复用（原局已问真验证）',
  },
  {
    id: 'yueDeGan',
    name: '月德',
    system: '六壬',
    family: '月',
    qifa: { kind: 'branchMap', table: YUEDE },
    status: '已验收',
    koujue: '三合月德干：寅午戌月丙、申子辰月壬、亥卯未月甲、巳酉丑月庚',
    sourceRef: 'docs/12 L3（校验未＝甲）＋引擎 YUEDE 同表 import 复用（原局已问真验证）',
    note: '干系（app 口径）；支系月德见 yueDeLr（用户裁决保留）',
  },
  {
    id: 'yueHe',
    name: '月合',
    system: '六壬',
    family: '月',
    qifa: { kind: 'branchMap', table: LIUHE },
    status: '已验收',
    koujue: '月建六合之支（未月＝午）',
    sourceRef: 'docs/12 L3（校验未＝午）',
  },
  {
    id: 'yueXing',
    name: '月刑',
    system: '六壬',
    family: '月',
    qifa: { kind: 'branchMap', table: XING },
    status: '已验收',
    koujue: '月建之刑（未刑丑）',
    sourceRef: 'docs/12 L3（校验未＝丑）',
  },
  {
    id: 'huaGaiYue',
    name: '华盖',
    system: '六壬',
    family: '月',
    qifa: { kind: 'branchMap', table: HUAGAI },
    status: '已验收',
    koujue: '月建三合墓辰（亥卯未月＝未）',
    sourceRef: 'docs/12 L3（校验未＝未）＋引擎 HUAGAI 同表 import 复用',
  },
  {
    id: 'xianChiYue',
    name: '咸池',
    system: '六壬',
    family: '月',
    qifa: { kind: 'branchMap', table: TAOHUA },
    status: '已验收',
    koujue: '月建三合沐浴（亥卯未月＝子）',
    sourceRef: 'docs/12 L3（校验未＝子）＋引擎 TAOHUA 同表 import 复用',
  },
  {
    id: 'guanFuYue',
    name: '官符',
    system: '六壬',
    family: '月',
    qifa: { kind: 'offset', n: 4 },
    status: '已验收',
    koujue: '月前四辰（未月＝亥；与岁前十二神官符同法换月锚）',
    sourceRef: 'docs/12 L3（校验未＝亥）',
  },
  // ── 旬族新增（4，旬遁干） ──
  {
    id: 'xunDing',
    name: '旬丁',
    system: '六壬',
    family: '旬',
    qifa: { kind: 'xunDun', gan: '丁' },
    status: '已验收',
    koujue: '本旬遁干得丁之支（甲辰旬＝丁未）',
    sourceRef: 'docs/12 L4（校验甲辰旬＝丁未）＋docs/11:82（原默认不做，用户以 app 点名启用）',
  },
  {
    id: 'xiangDong',
    name: '响动',
    aliases: ['旬庚'],
    system: '六壬',
    family: '旬',
    qifa: { kind: 'xunDun', gan: '庚' },
    status: '已验收',
    koujue: '本旬遁干得庚之支（甲辰旬＝庚戌）',
    sourceRef: 'docs/12 L4（校验甲辰旬＝庚戌）',
  },
  {
    id: 'biKou',
    name: '闭口',
    aliases: ['旬癸'],
    system: '六壬',
    family: '旬',
    qifa: { kind: 'xunDun', gan: '癸' },
    status: '已验收',
    koujue: '本旬遁干得癸之支（甲辰旬＝癸丑）',
    sourceRef: 'docs/12 L4（校验甲辰旬＝癸丑）',
  },
  {
    id: 'wuWangShen',
    name: '五亡神',
    aliases: ['旬辛'],
    system: '六壬',
    family: '旬',
    qifa: { kind: 'xunDun', gan: '辛' },
    status: '已验收',
    koujue: '本旬遁干得辛之支（甲辰旬＝辛亥）',
    sourceRef: 'docs/12 L4（校验甲辰旬＝辛亥）',
  },
  // ── 日干族新增（3） ──
  {
    id: 'riYi',
    name: '日医',
    system: '六壬',
    family: '日干',
    qifa: {
      kind: 'stemMap',
      table: { 甲: '卯', 乙: '亥', 丙: '丑', 丁: '未', 戊: '巳', 己: '卯', 庚: '亥', 辛: '丑', 壬: '未', 癸: '巳' },
    },
    status: '已验收',
    koujue: '甲卯乙亥丙丑丁未戊巳、己卯庚亥辛丑壬未癸巳',
    sourceRef: 'docs/11:98（原中置信单源）＋docs/12 L5（校验戊＝巳）——app 佐证转实',
  },
  {
    id: 'youDu',
    name: '游都',
    system: '六壬',
    family: '日干',
    qifa: {
      kind: 'stemMap',
      table: { 甲: '丑', 己: '丑', 乙: '子', 庚: '子', 丙: '寅', 辛: '寅', 丁: '巳', 壬: '巳', 戊: '申', 癸: '申' },
    },
    status: '已验收',
    koujue: '甲己丑、乙庚子、丙辛寅、丁壬巳、戊癸申',
    sourceRef: 'docs/11:95＋docs/12 L5（校验戊＝申）——原「默认不做」，用户以 app 点名启用',
  },
  {
    id: 'luDu',
    name: '鲁都',
    system: '六壬',
    family: '日干',
    qifa: {
      kind: 'stemMap',
      table: { 甲: '未', 己: '未', 乙: '午', 庚: '午', 丙: '申', 辛: '申', 丁: '亥', 壬: '亥', 戊: '寅', 癸: '寅' },
    },
    status: '已验收',
    koujue: '游都对冲',
    sourceRef: 'docs/12 L5（校验戊＝寅）',
    note: '独立转录表，「鲁都＝游都冲」派生关系交给不变量测试',
  },
  // ── 日支族新增（5） ──
  {
    id: 'liuHeRz',
    name: '六合',
    system: '六壬',
    family: '日支',
    qifa: { kind: 'branchMap', table: LIUHE },
    status: '已验收',
    koujue: '日支六合（申＝巳）',
    sourceRef: 'docs/12 L6（校验申＝巳）',
  },
  {
    id: 'sanHeRz',
    name: '三合',
    system: '六壬',
    family: '日支',
    qifa: { kind: 'branchMap', table: SANHE_REST },
    status: '已验收',
    koujue: '日支三合其余两支（申＝子辰）',
    sourceRef: 'docs/12 L6（校验申＝子辰）',
  },
  {
    id: 'huaGaiRz',
    name: '华盖',
    system: '六壬',
    family: '日支',
    qifa: { kind: 'branchMap', table: HUAGAI },
    status: '已验收',
    koujue: '日支三合墓辰（申子辰＝辰）',
    sourceRef: 'docs/12 L6（校验申＝辰）＋引擎 HUAGAI 同表 import 复用',
  },
  {
    id: 'taoHuaRz',
    name: '桃花',
    system: '六壬',
    family: '日支',
    qifa: { kind: 'branchMap', table: TAOHUA },
    status: '已验收',
    koujue: '日支三合沐浴（申子辰＝酉）',
    sourceRef: 'docs/12 L6（校验申＝酉）＋引擎 TAOHUA 同表 import 复用',
  },
  {
    id: 'jiangJunRz',
    name: '将军',
    system: '六壬',
    family: '日支',
    qifa: { kind: 'branchMap', table: JIANGXING },
    status: '已验收',
    koujue: '日支三合旺位（即将星：申子辰＝子）',
    sourceRef: 'docs/12 L6（校验申＝子）＋引擎 JIANGXING 同表 import 复用',
  },
  // ══ 2026-08-02 第三批（L 系列检索定表）：古籍起法＋app 校验值双源 ══
  // ── 月族（13） ──
  {
    id: 'ciHuSha',
    name: '雌虎煞',
    system: '六壬',
    family: '月',
    qifa: { kind: 'monthSeq', start: '辰', dir: 1 },
    mergeInto: { rule: 'tianWu' },
    status: '已验收',
    koujue: '正月起辰顺行十二辰（与天巫同位）',
    sourceRef: '六壬指南·神煞指南「辰 天医雌虎瘟天巫」＋docs/12 L3（校验未＝酉）',
  },
  {
    id: 'chanSha',
    name: '产煞',
    system: '六壬',
    family: '月',
    qifa: {
      kind: 'branchMap',
      table: { 寅: '寅', 卯: '巳', 辰: '申', 巳: '亥', 午: '寅', 未: '巳', 申: '申', 酉: '亥', 戌: '寅', 亥: '巳', 子: '申', 丑: '亥' },
    },
    status: '已验收',
    koujue: '正月起寅顺行四孟（寅巳申亥）',
    sourceRef: '六壬指南·神煞指南「寅巳申亥 釜产厕奸私」＋docs/12 L3（校验未＝巳）',
  },
  {
    id: 'jianMen',
    name: '奸门',
    system: '六壬',
    family: '月',
    qifa: {
      kind: 'branchMap',
      table: { 寅: '申', 卯: '亥', 辰: '寅', 巳: '巳', 午: '申', 未: '亥', 申: '寅', 酉: '巳', 戌: '申', 亥: '亥', 子: '寅', 丑: '巳' },
    },
    status: '已验收',
    koujue: '正月起申顺行四孟（申亥寅巳）',
    sourceRef: '大六壬神煞赋「正申进孟即奸门」＋docs/12 L3（校验未＝亥）',
  },
  {
    id: 'huoZhu',
    name: '火烛',
    system: '六壬',
    family: '月',
    qifa: { kind: 'monthSeq', start: '巳', dir: 1 },
    status: '已验收',
    koujue: '正月起巳顺行十二辰',
    sourceRef: '六壬指南·神煞指南「巳 厄杖死神电乌烛」＋docs/12 L3（校验未＝戌）',
  },
  {
    id: 'feiLianYue',
    name: '飞廉',
    aliases: ['飞廉(月系)'],
    system: '六壬',
    family: '月',
    qifa: {
      kind: 'branchMap',
      table: { 寅: '戌', 卯: '巳', 辰: '午', 巳: '未', 午: '寅', 未: '卯', 申: '辰', 酉: '亥', 戌: '子', 亥: '丑', 子: '申', 丑: '酉' },
    },
    status: '已验收',
    koujue: '正戌二巳三午四未五寅六卯七辰八亥九子十丑冬申腊酉（神煞赋歌诀）',
    sourceRef: '孟子翔《大六壬神煞赋详解》＋docs/12 L3（校验未＝卯）',
    note: '另一常见口径（五申六酉冬寅腊卯）未月＝酉与 app 不符，已舍；须与年系飞廉区分',
  },
  {
    id: 'tianGui',
    name: '天鬼',
    system: '六壬',
    family: '月',
    qifa: {
      kind: 'branchMap',
      table: { 寅: '酉', 卯: '午', 辰: '卯', 巳: '子', 午: '酉', 未: '午', 申: '卯', 酉: '子', 戌: '酉', 亥: '午', 子: '卯', 丑: '子' },
    },
    status: '已验收',
    koujue: '正月起酉逆行四仲（酉午卯子）',
    sourceRef: '六壬指南「酉午卯子 鬼吏长绳天咒接」＋docs/12 L3（校验未＝午）',
  },
  {
    id: 'tianGuai',
    name: '天怪',
    system: '六壬',
    family: '月',
    qifa: { kind: 'monthSeq', start: '丑', dir: -1 },
    status: '已验收',
    koujue: '正月起丑逆行十二辰',
    sourceRef: '六壬指南·神煞指南逆行章「丑 天怪占天变」＋docs/12 L3（校验未＝申）',
    note: '神煞赋另说「正午逆十二」未月＝丑与 app 不符，已舍',
  },
  {
    id: 'feiHun',
    name: '飞魂',
    system: '六壬',
    family: '月',
    qifa: { kind: 'monthSeq', start: '亥', dir: 1 },
    mergeInto: { rule: 'tianZhao' },
    status: '已验收',
    koujue: '月建后三位，正月起亥顺行十二辰（与天诏同位）',
    sourceRef: '六壬指南「亥 飞魂伏语病儿哭」＋docs/12 L3（校验未＝辰）',
  },
  {
    id: 'leiGong',
    name: '雷公',
    system: '六壬',
    family: '月',
    qifa: {
      kind: 'branchMap',
      table: { 寅: '寅', 卯: '亥', 辰: '申', 巳: '巳', 午: '寅', 未: '亥', 申: '申', 酉: '巳', 戌: '寅', 亥: '亥', 子: '申', 丑: '巳' },
    },
    status: '已验收',
    koujue: '正月起寅逆行四孟（寅亥申巳）',
    sourceRef: '大六壬神煞赋「虎逆雷公四孟取」＋docs/12 L3（校验未＝亥）',
  },
  {
    id: 'leiSha',
    name: '雷煞',
    system: '六壬',
    family: '月',
    qifa: {
      kind: 'branchMap',
      table: { 寅: '亥', 卯: '申', 辰: '巳', 巳: '寅', 午: '亥', 未: '申', 申: '巳', 酉: '寅', 戌: '亥', 亥: '申', 子: '巳', 丑: '寅' },
    },
    mergeInto: { rule: 'muMen' },
    status: '已验收',
    koujue: '正月起亥逆行四孟（亥申巳寅），与墓门同位',
    sourceRef: '大六壬神煞赋「雷煞正猪逆孟流」＋docs/12 L3（校验未＝申）',
  },
  {
    id: 'fengBo',
    name: '风伯',
    system: '六壬',
    family: '月',
    qifa: { kind: 'monthSeq', start: '申', dir: -1 },
    status: '已验收',
    koujue: '正月起申逆行十二辰',
    sourceRef: '大六壬神煞赋「欲安风伯从猴逆」＋docs/12 L3（校验未＝卯）',
  },
  {
    id: 'fengSha',
    name: '风煞',
    system: '六壬',
    family: '月',
    qifa: { kind: 'monthSeq', start: '寅', dir: -1 },
    status: '已验收',
    koujue: '正月起寅逆行十二辰',
    sourceRef: '大六壬神煞赋「一轮风煞虎回头」＋docs/12 L3（校验未＝酉）',
    note: '六壬大全另有「风煞申逆十二」（与风伯同起）未月＝卯与 app 不符，已舍',
  },
  {
    id: 'yuSha',
    name: '雨煞',
    system: '六壬',
    family: '月',
    qifa: { kind: 'monthSeq', start: '子', dir: 1 },
    mergeInto: { rule: 'shengQi' },
    status: '已验收',
    koujue: '与生气同位：正月起子顺行十二辰',
    sourceRef: '六壬指南「生气子正雨煞来」＋大六壬神煞赋「原来雨煞同生气」；2026-08-02 用户裁决从古籍不从 app',
    note: 'app 名「雨煞」者实为月系雨师（正子顺四仲）——用户裁决本条取古籍本义，app 那一支另立 yuShiYue',
  },
  {
    id: 'yuShiYue',
    name: '雨师',
    system: '六壬',
    family: '月',
    qifa: {
      kind: 'branchMap',
      table: { 寅: '子', 卯: '卯', 辰: '午', 巳: '酉', 午: '子', 未: '卯', 申: '午', 酉: '酉', 戌: '子', 亥: '卯', 子: '午', 丑: '酉' },
    },
    status: '已验收',
    koujue: '正月起子，顺行四仲（子卯午酉）',
    sourceRef: '六壬指南·神煞辨讹「雨师正子顺四仲者是，余说非」＋大六壬神煞赋「雨师仲顺鼠先求」；app 于此位显示未月＝卯',
    note: '月系雨师，与日支系雨师（子日起申）及月系雨煞（＝生气同位）三者互异，《指南》明辨',
  },
  // ── 日干族（9） ──
  {
    id: 'wuHe',
    name: '五合',
    system: '六壬',
    family: '日干',
    qifa: {
      kind: 'stemMap',
      table: { 甲: '未', 乙: '申', 丙: '戌', 丁: '亥', 戊: '丑', 己: '寅', 庚: '辰', 辛: '巳', 壬: '未', 癸: '巳' },
    },
    status: '已验收',
    koujue: '日干五合之干的寄宫（甲合己·己寄未…戊合癸·癸寄丑）',
    sourceRef: '大六壬神煞指南干煞表「合 未申戌亥丑寅辰巳未巳」＋docs/12 L5（校验戊＝丑）',
  },
  {
    id: 'changSheng',
    name: '长生',
    system: '六壬',
    family: '日干',
    qifa: {
      kind: 'stemMap',
      table: { 甲: '亥', 乙: '亥', 丙: '寅', 丁: '寅', 戊: '申', 己: '申', 庚: '巳', 辛: '巳', 壬: '申', 癸: '申' },
    },
    status: '已验收',
    koujue: '五行长生：木生亥、火生寅、金生巳、水土生申（阴阳干同位，有顺无逆）',
    sourceRef: '大六壬神煞指南「长生亥亥寅寅申申巳巳申申」＋六壬大全卷一长生乘墓例＋docs/12 L5（校验戊＝申）',
    note: '子平「阳顺阴逆」口径在乙丁己辛癸位不同（乙午丁酉己酉辛子癸卯）——戊位无法区分，建议用乙日在 app 复核',
  },
  {
    id: 'xueTangLr',
    name: '学堂',
    aliases: ['学堂(六壬)'],
    system: '六壬',
    family: '日干',
    qifa: {
      kind: 'stemMap',
      table: { 甲: '亥', 乙: '亥', 丙: '寅', 丁: '寅', 戊: '申', 己: '申', 庚: '巳', 辛: '巳', 壬: '申', 癸: '申' },
    },
    mergeInto: { rule: 'changSheng' },
    status: '已验收',
    koujue: '长生之正位（三命通会：生乃学堂之正位），与长生同位',
    sourceRef: '三命通会·论学堂词馆＋docs/12 L5（校验戊＝申）',
    note: '与八字学堂（纳音五行起、正配干支）同名异煞；十干干支专位口径戊＝寅与 app 不符已舍',
  },
  {
    id: 'xianGui',
    name: '贤贵',
    system: '六壬',
    family: '日干',
    qifa: {
      kind: 'stemMap',
      table: { 甲: '丑', 己: '丑', 乙: '申', 庚: '申', 丙: '寅', 辛: '寅', 丁: '寅', 壬: '寅', 戊: '午', 癸: '午' },
    },
    status: '已验收',
    koujue: '甲己丑、乙庚申、丙辛寅、丁壬寅、戊癸午',
    sourceRef: '大六壬神煞指南「贤贵丑申寅寅午」＋docs/12 L5（校验戊＝午）',
  },
  {
    id: 'jianWu',
    name: '兼务',
    system: '六壬',
    family: '日干',
    qifa: {
      kind: 'stemMap',
      table: { 甲: '戌', 乙: '酉', 丙: '申', 丁: '未', 戊: '午', 己: '巳', 庚: '辰', 辛: '卯', 壬: '寅', 癸: '丑' },
    },
    status: '已验收',
    koujue: '甲戌起逆行十干（甲戌乙酉丙申丁未戊午己巳庚辰辛卯壬寅癸丑）',
    sourceRef: '大六壬神煞指南「癸干亥逆兼务举」（取其逆行方向）＋docs/12 L5/L8 三锚定表（戊午、乙酉、庚辰）',
    note: '字面读「癸起亥逆数」得乙卯/庚申，被 app 乙日与庚日两张截图否定；三锚共线唯一确定甲戌起逆',
  },
  {
    id: 'jinShenLr',
    name: '进神',
    aliases: ['进神(六壬)'],
    system: '六壬',
    family: '日干',
    qifa: {
      kind: 'stemMap',
      table: { 甲: ['子', '午'], 乙: ['子', '午'], 丙: ['子', '午'], 丁: ['子', '午'], 戊: ['子', '午'], 己: ['卯', '酉'], 庚: ['卯', '酉'], 辛: ['卯', '酉'], 壬: ['卯', '酉'], 癸: ['卯', '酉'] },
    },
    status: '已验收',
    koujue: '甲乙丙丁戊日子午为进神；己庚辛壬癸日卯酉为进神',
    sourceRef: '大六壬神煞指南「进神子午卯兼酉」＋docs/12 L5（校验戊＝子午）',
    note: '与八字进神（甲子甲午己卯己酉四日柱）同名异煞；「阳日子午/阴日卯酉」口径在乙丁庚壬位不同——戊位无法区分，建议用乙日或庚日在 app 复核',
  },
  {
    id: 'tuiShenLr',
    name: '退神',
    aliases: ['退神(六壬)'],
    system: '六壬',
    family: '日干',
    qifa: {
      kind: 'stemMap',
      table: { 甲: ['丑', '未'], 乙: ['丑', '未'], 丙: ['丑', '未'], 丁: ['丑', '未'], 戊: ['丑', '未'], 己: ['辰', '戌'], 庚: ['辰', '戌'], 辛: ['辰', '戌'], 壬: ['辰', '戌'], 癸: ['辰', '戌'] },
    },
    status: '已验收',
    koujue: '甲乙丙丁戊日丑未为退神；己庚辛壬癸日辰戌为退神',
    sourceRef: '大六壬神煞指南「丑未戌辰退莫难」＋docs/12 L5（校验戊＝丑未）',
    note: '与八字退神（丁丑丁未壬辰壬戌四日柱）同名异煞；同进神，建议乙/庚日复核',
  },
  {
    id: 'riJie',
    name: '日解',
    system: '六壬',
    family: '日干',
    qifa: {
      kind: 'stemMap',
      table: { 甲: '亥', 己: '亥', 乙: '申', 庚: '申', 丙: '未', 辛: '未', 丁: '丑', 壬: '丑', 戊: '酉', 癸: '酉' },
    },
    status: '已验收',
    koujue: '甲己亥、乙庚申、丙辛未、丁壬丑、戊癸酉',
    sourceRef: '大六壬神煞指南「亥申未丑酉日解」＋docs/12 L5（校验戊＝酉）',
    note: '勿与月系解神混同（彼为月煞）',
  },
  {
    id: 'riXing',
    name: '日刑',
    system: '六壬',
    family: '日干',
    qifa: {
      kind: 'stemMap',
      table: { 甲: '巳', 乙: '辰', 丙: '申', 丁: '丑', 戊: '申', 己: '丑', 庚: '寅', 辛: '未', 壬: '亥', 癸: '戌' },
    },
    status: '已验收',
    koujue: '日干寄宫所刑之支（甲寄寅·寅刑巳；戊寄巳·巳刑申）',
    sourceRef: '大六壬神煞指南「刑冲支位寄官论」＋docs/12 L5（校验戊＝申）',
    note: '「禄位之刑」口径在阴干位不同（乙子丁午己午辛酉癸卯）——戊位无法区分，建议用乙日在 app 复核',
  },
  // ── 补漏与口径定案（4）──
  {
    id: 'zhiDe',
    name: '支德',
    system: '六壬',
    family: '日支',
    qifa: { kind: 'offset', n: 5 },
    status: '已验收',
    koujue: '支前五辰（申日＝丑）',
    sourceRef: 'docs/11:112（原中置信单源）＋docs/12 L6（校验申＝丑）——app 佐证转实',
  },
  {
    id: 'tianYiLr',
    name: '天医',
    aliases: ['天医(六壬)'],
    system: '六壬',
    family: '月',
    qifa: {
      kind: 'branchMap',
      table: { 寅: '子', 卯: '卯', 辰: '午', 巳: '酉', 午: '子', 未: '卯', 申: '午', 酉: '酉', 戌: '子', 亥: '卯', 子: '午', 丑: '酉' },
    },
    status: '已验收',
    koujue: '子卯午酉三轮（正月子，四仲顺行）',
    sourceRef: 'docs/11:65（三口径互斥）＋docs/12 L3（校验未＝卯）——app 定案取三轮口径',
    note: '另两口径（正月辰顺行／月建后四）与 app 不符已舍；与八字天医（月支后一，引擎原局已有）同名异煞',
  },
  {
    id: 'huangEn',
    name: '皇恩',
    system: '六壬',
    family: '月',
    qifa: {
      kind: 'branchMap',
      table: { 寅: '未', 卯: '酉', 辰: '亥', 巳: '丑', 午: '卯', 未: '巳', 申: '未', 酉: '酉', 戌: '亥', 亥: '丑', 子: '卯', 丑: '巳' },
    },
    status: '已验收',
    koujue: '正月起未，顺行六阴辰（未酉亥丑卯巳）',
    sourceRef: 'docs/11:66（两口径）＋docs/12 L3（校验未＝巳）——app 定案取六阴口径',
    note: '六壬大全逐位表口径（正戌二丑三辰…）与 app 不符已舍',
  },
  {
    id: 'siShen',
    name: '死神',
    system: '六壬',
    family: '月',
    qifa: { kind: 'monthSeq', start: '巳', dir: 1 },
    status: '已验收',
    koujue: '正月起巳顺行十二辰',
    sourceRef: 'docs/11:68（两口径）＋docs/12 L3（校验未＝戌）——app 定案取六壬大全口径',
    note: '简书「死气后一位」口径与 app 不符已舍',
  },
  // ══ 2026-08-02 第四批（检索续跑）：月族 17 ＋ 日支族 3 ══
  {
    id: 'huiShen',
    name: '会神',
    system: '六壬',
    family: '月',
    qifa: {
      kind: 'branchMap',
      table: { 寅: '未', 卯: '戌', 辰: '寅', 巳: '亥', 午: '酉', 未: '子', 申: '丑', 酉: '午', 戌: '巳', 亥: '卯', 子: '申', 丑: '辰' },
    },
    status: '已验收',
    koujue: '未戌寅亥酉子丑午巳卯申辰（无规律，逐位背）',
    sourceRef: '六壬大全卷一十二月神煞＋六壬指南卷四＋神煞赋，三家全同；docs/12 L3（校验未＝子）',
  },
  {
    id: 'tianCai',
    name: '天财',
    system: '六壬',
    family: '月',
    qifa: {
      kind: 'branchMap',
      table: { 寅: '辰', 卯: '午', 辰: '申', 巳: '戌', 午: '子', 未: '寅', 申: '辰', 酉: '午', 戌: '申', 亥: '戌', 子: '子', 丑: '寅' },
    },
    status: '已验收',
    koujue: '正月起辰，顺行六阳辰（辰午申戌子寅）',
    sourceRef: '神煞赋「天财六阳正顺辰」＋六壬指南「天财正七辰阳遵」；docs/12 L3（校验未＝寅）',
  },
  {
    id: 'xinShen',
    name: '信神',
    system: '六壬',
    family: '月',
    qifa: {
      kind: 'branchMap',
      table: { 寅: '申', 卯: '戌', 辰: '寅', 巳: '丑', 午: '亥', 未: '辰', 申: '巳', 酉: '未', 戌: '巳', 亥: '未', 子: '申', 丑: '戌' },
    },
    status: '已验收',
    koujue: '申戌寅丑亥辰巳未巳未申戌（无规律，逐位背）',
    sourceRef: '六壬大全卷一＋六壬指南卷四神煞全图；docs/12 L3（校验未＝辰）',
    note: '另有「正酉逆十二」口径在未月同值（辰），须用二月锚复核（本表＝戌，逆行说＝申）',
  },
  {
    id: 'daShe',
    name: '大赦',
    aliases: ['皇恩大赦'],
    system: '六壬',
    family: '月',
    qifa: {
      kind: 'branchMap',
      table: { 寅: '戌', 卯: '丑', 辰: '辰', 巳: '未', 午: '卯', 未: '酉', 申: '子', 酉: '午', 戌: '亥', 亥: '寅', 子: '巳', 丑: '申' },
    },
    status: '已验收',
    koujue: '戌丑辰未卯酉子午亥寅巳申（四季＋四仲＋四孟三段）',
    sourceRef: '六壬大全卷一（逐月神煞十一处印证）＋六壬指南韵语「皇恩大赦戌丑罡」；docs/12 L3（校验未＝酉）',
    note: '古籍本名「皇恩」，app 拆名为大赦；六壬指南神煞全图异文（五六月互易）与 app 不符已舍',
  },
  {
    id: 'tianEn',
    name: '天恩',
    system: '六壬',
    family: '月',
    qifa: {
      kind: 'branchMap',
      table: { 寅: '未', 卯: '酉', 辰: '亥', 巳: '丑', 午: '卯', 未: '巳', 申: '未', 酉: '酉', 戌: '亥', 亥: '丑', 子: '卯', 丑: '巳' },
    },
    status: '已验收',
    koujue: '正月起未，顺行六阴辰（未酉亥丑卯巳）',
    sourceRef: '神煞赋「六阴正未皇恩顺」＋六壬指南；docs/12 L3（校验未＝巳）',
    note: '古籍带全表者名「皇恩」；六壬大全逐月神煞另有「天恩」仅一处（疑季煞春寅夏巳秋申冬亥），两说未月同值——建议用四月或五月锚复核',
  },
  {
    id: 'diYi',
    name: '地医',
    system: '六壬',
    family: '月',
    qifa: { kind: 'monthSeq', start: '子', dir: 1 },
    mergeInto: { rule: 'shengQi' },
    status: '已验收',
    koujue: '正月起子顺行十二辰（与生气同位）',
    sourceRef: '六壬大全卷一逐月神煞（十一个月份印证地医与生气同位）；docs/12 L3（校验未＝巳）',
    note: '通行「天医所冲、正月起戌」口径未月＝卯与 app 不符已舍——本组天医/地医均从六壬大全',
  },
  {
    id: 'tianJieShen',
    name: '天解神',
    system: '六壬',
    family: '月',
    qifa: { kind: 'monthSeq', start: '申', dir: -1 },
    status: '已验收',
    koujue: '正月起申逆行十二辰',
    sourceRef: '六壬指南卷四「天解正申逆十二」；docs/12 L3（校验未＝卯）',
    note: '另三口径（六壬大全六阳辰／神煞赋两月一位）均与 app 不符已舍',
  },
  {
    id: 'diJieShen',
    name: '地解神',
    system: '六壬',
    family: '月',
    qifa: {
      kind: 'branchMap',
      table: { 寅: '申', 卯: '申', 辰: '酉', 巳: '酉', 午: '戌', 未: '戌', 申: '亥', 酉: '亥', 戌: '午', 亥: '午', 子: '未', 丑: '未' },
    },
    status: '已验收',
    koujue: '申申酉酉戌戌亥亥午午未未（两月一位，九月起跳至午）',
    sourceRef: '六壬指南卷四神煞全图＋六壬大全同行值（名「解神」）；docs/12 L3（校验未＝戌）',
  },
  {
    id: 'huoTianShe',
    name: '活天赦',
    system: '六壬',
    family: '月',
    qifa: {
      kind: 'branchMap',
      table: { 寅: '未', 卯: '戌', 辰: '丑', 巳: '辰', 午: '未', 未: '戌', 申: '丑', 酉: '辰', 戌: '未', 亥: '戌', 子: '丑', 丑: '辰' },
    },
    status: '已验收',
    koujue: '正月起未，顺行四季（未戌丑辰）',
    sourceRef: '六壬大全卷一逐月神煞（九个月份印证）；docs/12 L3（校验未＝戌）',
    note: '别于干支天赦「死天赦」（春戊寅夏甲午秋戊申冬甲子，即本表 tianSheDyn）',
  },
  {
    id: 'zhangSheng',
    name: '长绳',
    system: '六壬',
    family: '月',
    qifa: {
      kind: 'branchMap',
      table: { 寅: '酉', 卯: '午', 辰: '卯', 巳: '子', 午: '酉', 未: '午', 申: '卯', 酉: '子', 戌: '酉', 亥: '午', 子: '卯', 丑: '子' },
    },
    mergeInto: { rule: 'tianGui' },
    status: '已验收',
    koujue: '正月起酉，逆行四仲（酉午卯子），与天鬼同位',
    sourceRef: '六壬指南卷四「酉午卯子 鬼吏长绳天咒接」＋伊凡子＋南离生三家一致；docs/12 L3（校验未＝午）',
    note: '六壬大全「长绳亥逆十二」口径在未月同值（午），须用正月或二月锚复核（本表＝酉，大全说＝亥）',
  },
  {
    id: 'xuanSuo',
    name: '悬索',
    system: '六壬',
    family: '月',
    qifa: {
      kind: 'branchMap',
      table: { 寅: '卯', 卯: '子', 辰: '酉', 巳: '午', 午: '卯', 未: '子', 申: '酉', 酉: '午', 戌: '卯', 亥: '子', 子: '酉', 丑: '午' },
    },
    mergeInto: { rule: 'xianChiYue' },
    status: '已验收',
    koujue: '正月起卯，逆行四仲（卯子酉午），与咸池同位',
    sourceRef: '六壬指南卷四「卯子酉午 桃池悬索大时煞」；docs/12 L3（校验未＝子）',
  },
  {
    id: 'tianShu',
    name: '天鼠',
    system: '六壬',
    family: '月',
    qifa: { kind: 'monthSeq', start: '子', dir: -1 },
    status: '已验收',
    koujue: '正月起子逆行十二辰',
    sourceRef: '六壬指南卷四「子 鼠视捕追良」＋神煞辨讹「鼠畏缩故逆行，顺者非」；docs/12 L3（校验未＝未）',
  },
  {
    id: 'tianJi',
    name: '天鸡',
    system: '六壬',
    family: '月',
    qifa: { kind: 'monthSeq', start: '酉', dir: -1 },
    status: '已验收',
    koujue: '正月起酉逆行十二辰',
    sourceRef: '六壬指南卷四「酉 轩辕天鸡折」＋伊凡子＋南离生；docs/12 L3（校验未＝辰）',
  },
  {
    id: 'daSha',
    name: '大煞',
    system: '六壬',
    family: '月',
    qifa: {
      kind: 'branchMap',
      table: { 寅: '午', 卯: '卯', 辰: '子', 巳: '酉', 午: '午', 未: '卯', 申: '子', 酉: '酉', 戌: '午', 亥: '卯', 子: '子', 丑: '酉' },
    },
    status: '已验收',
    koujue: '正月起午，逆行四仲（午卯子酉）＝月建三合旺气（将星位）',
    sourceRef: '六壬指南卷四神煞辨讹「大煞为三合旺气，正午逆四仲者是，正戌逆四季者非」＋伊凡子＋南离生＋孟子翔注；2026-08-02 用户指示「按指南来」',
    note: '⚠️与 app 显示不一致：app 三锚（未月未／寅月戌／申月辰）全部指向辨讹篇判为「非」的另一支（正戌逆四季 戌未辰丑）。用户明示从指南故取正解——要改回 app 口径换回四季表即可',
  },
  {
    id: 'miHuo',
    name: '迷惑',
    system: '六壬',
    family: '月',
    qifa: {
      kind: 'branchMap',
      table: { 寅: '丑', 卯: '戌', 辰: '未', 巳: '辰', 午: '丑', 未: '戌', 申: '未', 酉: '辰', 戌: '丑', 亥: '戌', 子: '未', 丑: '辰' },
    },
    status: '已验收',
    koujue: '正月起丑，逆行四季（丑戌未辰）',
    sourceRef: '六壬指南卷四「丑戌未辰 五盗小天迷惑月」＋神煞辨讹「正丑逆季者是，逆十二者非」；docs/12 L3（校验未＝戌）',
  },
  {
    id: 'sangCheYue',
    name: '丧车',
    system: '六壬',
    family: '月',
    qifa: {
      kind: 'branchMap',
      table: { 寅: '未', 卯: '辰', 辰: '丑', 巳: '戌', 午: '未', 未: '辰', 申: '丑', 酉: '戌', 戌: '未', 亥: '辰', 子: '丑', 丑: '戌' },
    },
    status: '已验收',
    koujue: '正月起未，逆行四季（未辰丑戌），一名丧魂',
    sourceRef: '六壬大全卷九灾厄课「丧车一名丧魂，正月起未，逆行四季」；docs/12 L3（校验未＝辰）',
    note: '与季系「丧车煞」（＝四废同位，春酉夏子秋卯冬午）同名异煞，app 亦分列两条',
  },
  {
    id: 'kuGu',
    name: '枯骨',
    system: '六壬',
    family: '月',
    qifa: { kind: 'monthSeq', start: '未', dir: 1 },
    status: '已验收',
    koujue: '正月起未顺行十二辰',
    sourceRef: '六壬指南卷四「未 井枯小耗印羊福」＋神煞辨讹「正未顺十二者是，正申正辰俱非」；docs/12 L3（校验未＝子）',
  },
  // ── 日支族（3，占天时用） ──
  {
    id: 'leiDian',
    name: '雷电',
    system: '六壬',
    family: '日支',
    qifa: {
      kind: 'branchMap',
      table: { 子: '辰', 丑: '辰', 寅: '未', 卯: '未', 辰: '戌', 巳: '戌', 午: '丑', 未: '丑', 申: '寅', 酉: '寅', 戌: '卯', 亥: '卯' },
    },
    status: '已验收',
    koujue: '辰未戌丑寅卯双双排（两支一位，占天时用）',
    sourceRef: '六壬指南卷四支煞歌「双双雷电空中作」；docs/12 L6（校验申＝寅）',
    note: '与月系雷煞/雷公同名异法（彼按月支起）',
  },
  {
    id: 'yuShi',
    name: '雨师',
    system: '六壬',
    family: '日支',
    qifa: { kind: 'offset', n: 8 },
    status: '已验收',
    koujue: '子日起申顺行十二辰（申为水母）',
    sourceRef: '六壬指南卷四支煞歌「雨师申顺滂沱落」，注「此与月煞不同」；docs/12 L6（校验申＝辰）',
    note: '与月系雨煞（正月起子顺四仲）同名异法，指南明言二者不同',
  },
  {
    id: 'qingLang',
    name: '晴朗',
    system: '六壬',
    family: '日支',
    qifa: { kind: 'offset', n: 6 },
    mergeInto: { rule: 'zhiChong' },
    status: '已验收',
    koujue: '日支冲辰（子日起午，顺行十二辰），与六冲同位',
    sourceRef: '伊凡子六壬神煞整理＋六壬指南「明朗午宫日影灼」；docs/12 L6（校验申＝寅）',
  },
]

export { SANHE_JIE }
